Algoritmo "Fahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Conversor de graus Farenheit em Celsius
// Autor(a)    : Davi Machado
// Data atual  : 19/03/2024
Var
// Seção de Declarações das variáveis 
f: real
c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a temperatura em Fº: ")
leia(f)
c<-((f-32)*5/9)
Escreva("Temperatura em Celsius é: ",c,"°")

Fimalgoritmo