Algoritmo "Fahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Conversor de graus Farenheit em Celsius
// Autor(a)    : Davi Machado
// Data atual  : 19/03/2024
Var
// Seção de Declarações das variáveis 
f: real
c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a temperatura em Cº: ")
leia(c)
f<-((9*c+160)/5)
Escreva("Temperatura em Farenheit é: ",f,"°")

Fimalgoritmo