Algoritmo "7g - propriedade distributiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calculo de adição e multiplicação, utilizando do conceito de propriedade distributiva em 4 variaveis
// Autor(a)    : Davi Machado
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
a, b, c, d: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



Fimalgoritmo