Algoritmo "L05A"
// Disciplina   : Linguagem de Programação Java
// Professor   : Jailson 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Davi Machado
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de  15 ate 200 passo 1 faca
escreval(numero^2)
timer 22
fimpara

Fimalgoritmo